name: Publish CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Download dependencies 🔧
        run: yarn

      - name: Pre-build
        run: script/addEditLinks.py

      - name: Build 🔧
        run: PUBLIC_URL=/techradar yarn build

      - name: Build Static site 🔧
        run: PUBLIC_URL=/techradar yarn build-static
      
      - name: Generate Data 🔧
        run: yarn generate-json

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true